name: 'github workflows bot'
description: 'manage github workflows'
inputs:
  github-token:  
    description: 'The GITHUB_TOKEN secret'
    required: true
  sync-labels:
    description: 'Whether or not to remove labels when matching files are reverted'
    default: false
    required: false
  keywords-labels:
    description: 'a map from keywords to labels'
    default: '.github/labeler.yml'
runs:
  using: 'node12'
  main: 'dist/index.js'