on:
  issues:
    types:[opened, reopend, edited]
  pull_request:
    types:[opened, reopend, edited]

jobs:
  bot:
    runs-on: ubuntu-latest
    name: A bot
    steps:
      # To use this repository's private action,
      # you must check out the repository
      - name: Checkout
        uses: actions/checkout@v2
      - name: run
        uses: ./ # Uses an action in the root directory
        id: hello
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
      # Use the output from the `hello` step
      - name: Get the output time
        run: echo "The time was ${{ steps.hello.outputs.time }}"